[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_counter = "5U44h9RTCKSm1vCTn6pjhS8xQofxFv27tjzh1zxqD58k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/tolgaand/twitter-wallet/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
